AppCfg:
  Name: "user-api"
  Namespace: "go.micro.tc"
  Version: "V0.001"
CfgEtcd:
  Addr:
    - "127.0.0.1:2379"
    - "127.0.0.1:2379"
  User: ""
  Passwd: ""
  PathPrefix: "/gateway/config"
RegEtcd:
  Addr:
    - "127.0.0.1:2379"
    - "127.0.0.1:2379"
  User: ""
  Passwd: ""
Trace:
  Addr: ""
